# Generated by Django 3.0.5 on 2024-03-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('optimal_temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('optimal_humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('planting_season', models.CharField(max_length=100)),
                ('harvesting_season', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SoilContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitrogen', models.FloatField()),
                ('phosphorus', models.FloatField()),
                ('potassium', models.FloatField()),
                ('ph_level', models.FloatField()),
            ],
        ),
    ]
